# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

sudo: false
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
env:
  - DJANGO="Django>=3,<3.1"
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=1.11,<1.12"
before_install:
  - pip install -q $DJANGO
install:
  - python setup.py develop
  - pip install -r requirements.test.txt .
script:
  - ./example/manage.py test
after_success:
  - coveralls
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=3,<3.1"
    - python: "3.4"
      env: DJANGO="Django>=3,<3.1"
    - python: "3.5"
      env: DJANGO="Django>=3,<3.1"

    - python: "3.4"
      env: DJANGO="Django>=2.2,<2.3"
    - python: "2.7"
      env: DJANGO="Django>=2.2,<2.3"
    - python: "3.8"
      env: DJANGO="Django>=2.2,<2.3"

    - python: "3.8"
      env: DJANGO="Django>=1.11,<1.12"
